FIELDS:

    T_MIN:
        type: decimal
        title:
            ru: Начальное значение температуры
        hint:
            ru: Введите начальное значение температуры тела в Кельвинах
        default: 100

    RAD_EX:
        type: decimal
        title:
            ru: Внешний радиус
        hint:
            ru: Введите значение внешнего радиуса тела в астрономических единицах
        min: 1
        default: 150

    RAD_IN:
        type: decimal
        title:
            ru: Внутренний радиус
        hint:
            ru: Введите значение внутреннего радиуса тела в астрономических единицах
        min: 1
        default: 100

    M:
        type: decimal
        title:
            ru: Масса 
        hint:
            ru: Введите массу тела в кг
        min: 1
        default: 150
        
    DEC_STEP_M:
        type: decimal
        title:
            ru: Степень десяти для массы
        hint:
            ru: В какой степени десяти измеряется масса тела
        min: 1
        default: 24

    DIMENSION:
        type: string
        title:
            ru: Графика
        hint:
            ru: В какой графике будет строиться фигура
        default: '3D'
        enum:
          - value: '3D'
            name:
                ru: 3D
          - value: '2D'
            name:
                ru: 2D
        
    

STRUCTURE:

- group:
        key: phys_settings
        title:  
            ru: Физические параметры тела
        fields:
            - field: DIMENSION
            - field: T_MIN
              width: full
            - field: RAD_EX
            - field: RAD_IN
            - field: M
            - field: DEC_STEP_M
            


UNITS:
    lenght:
        m:
            title:
                ru: Метры
            cm: 1
        mm:
            title:
                ru: Сантиметры
            m: 0.001
        cm:
            title:
                ru: Сантиметры
            m: 0.01
        km:
            title:
                ru: Сантиметры
            m: 1000